sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/', dependencies = TRUE)\""
sudo su - -c "R -e \"install.packages('gdata', repos='http://cran.rstudio.com/', dependencies = TRUE)\""
sudo su - -c "R -e \"install.packages('txtplot', repos='http://cran.rstudio.com/', dependencies = TRUE)\""
sudo su - -c "R -e \"install.packages('vegan', repos='http://cran.rstudio.com/', dependencies = TRUE)\""
sudo su - -c "R -e \"devtools::install_github('End-to-end-provenance/RDataTracker')\""
